"""add_ui_prefs_to_users

Revision ID: 036eb23e2efe
Revises: d43ff9d3ddac
Create Date: 2026-03-26 15:44:52.959484

"""
from alembic import op
import sqlalchemy as sa


revision = '036eb23e2efe'
down_revision = 'd43ff9d3ddac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ui_prefs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ui_prefs')
    # ### end Alembic commands ###
