"""add_projects_and_permissions

Revision ID: 5377ca9536c9
Revises: f85e4e982917
Create Date: 2026-03-26 11:05:23.597597

"""
from alembic import op
import sqlalchemy as sa


revision = '5377ca9536c9'
down_revision = 'f85e4e982917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status_enum'), nullable=False),
    sa.Column('archived_reason', sa.Enum('completed', 'abandoned', name='project_archived_reason_enum'), nullable=True),
    sa.Column('root_path', sa.String(length=500), nullable=True),
    sa.Column('docs_path', sa.String(length=500), nullable=True),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.Column('resume_summary', sa.Text(), nullable=False),
    sa.Column('agentic_dev', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('token_project_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('permission_level', sa.Enum('read', 'write', 'admin', name='permission_level_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'project_id', name='uq_token_project')
    )
    op.create_index(op.f('ix_token_project_permissions_project_id'), 'token_project_permissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_token_project_permissions_token_id'), 'token_project_permissions', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_project_permissions_token_id'), table_name='token_project_permissions')
    op.drop_index(op.f('ix_token_project_permissions_project_id'), table_name='token_project_permissions')
    op.drop_table('token_project_permissions')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
