"""add_tasks_and_activity_events

Revision ID: d43ff9d3ddac
Revises: 5377ca9536c9
Create Date: 2026-03-26 13:08:16.608016

"""
from alembic import op
import sqlalchemy as sa


revision = 'd43ff9d3ddac'
down_revision = '5377ca9536c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.Enum('human', 'agent', 'system', name='actor_type_enum'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_token_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_project_id'), 'activity_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_events_task_id'), 'activity_events', ['task_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('external_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'ready', 'in_progress', 'needs_review', 'blocked', 'done', 'cancelled', name='task_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='task_priority_enum'), nullable=False),
    sa.Column('owner_label', sa.String(length=50), nullable=False),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('abandoned_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_activity_events_task_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_project_id'), table_name='activity_events')
    op.drop_table('activity_events')
    # ### end Alembic commands ###
